## PCA Function Explanation

The `pca` function reduces the dimensionality of a dataset while retaining a specified fraction of its variance (`var`).

### Key Intuition
- PCA finds directions of maximum variance (principal components) in the data.
- Projecting data onto these directions reduces dimensions while preserving most of the information.

### SVD Decomposition
```python
U, S, Vh = np.linalg.svd(X)
V = Vh.T
````

* **`U`**: left singular vectors, captures patterns across data points (rows of `X`).
* **`S`**: singular values, indicate variance along each principal direction.
* **`Vh`**: right singular vectors (transposed), contains principal directions as rows.
* **`V = Vh.T`**: transposed so that each **column of `V` is a principal component**, ready for projecting the data.


### Steps

1. **Compute Cumulative Variance**

```python
cumsum = np.cumsum(S)
cumsum /= cumsum[-1]
```

* Determines the fraction of total variance captured by each component.

2. **Select Components**

```python
r = np.where(cumsum >= var)[0][0]
```

* Finds the minimum number of components needed to reach the desired variance fraction.

3. **Return Weight Matrix**

```python
return V[:, :r + 1]
```

* `W` can be used to reduce dimensionality: `X @ W`.


### Summary

* Performs SVD to extract principal directions and variance.
* Chooses enough components to retain the target variance.
* Returns a projection matrix for dimensionality reduction.


In [9]:
#!/usr/bin/env python3
"""PCA Module"""
import numpy as np


def pca(X, var=0.95):
    """Performs PCA on a dataset:
    """
    U, S, Vh = np.linalg.svd(X)

    V = Vh.T

    cumsum = np.cumsum(S)
    cumsum /= cumsum[-1]

    r = np.where(cumsum >= var)[0][0]

    return V[:, :r + 1]

In [11]:
np.random.seed(0)
a = np.random.normal(size=50)
b = np.random.normal(size=50)
c = np.random.normal(size=50)
d = 2 * a
e = -5 * b
f = 10 * c

X = np.array([a, b, c, d, e, f]).T
m = X.shape[0]
X_m = X - np.mean(X, axis=0)
W = pca(X_m)
T = np.matmul(X_m, W)
print(T)
X_t = np.matmul(T, W.T)
print(np.sum(np.square(X_m - X_t)) / m)

[[-16.71379391   3.25277063  -3.21956297]
 [ 16.22654311  -0.7283969   -0.88325252]
 [ 15.05945199   3.81948929  -1.97153621]
 [ -7.69814111   5.49561088  -4.34581561]
 [ 14.25075197   1.37060228  -4.04817187]
 [-16.66888233  -3.77067823   2.6264981 ]
 [  6.71765183   0.18115089  -1.91719288]
 [ 10.20004065  -0.84380128   0.44754302]
 [-16.93427229   1.72241573   0.9006236 ]
 [-12.4100987    0.75431367  -0.36518129]
 [-16.40464248   1.98431953   0.34907508]
 [ -6.69439671   1.30624703  -2.77438892]
 [ 10.84363895   4.99826372  -1.36502623]
 [-17.2656016    7.29822621   0.63226953]
 [  5.32413372  -0.54822516  -0.79075935]
 [ -5.63240657   1.50278876  -0.27590797]
 [ -7.63440366   7.72788006  -2.58344477]
 [  4.3348786   -2.14969035   0.61262033]
 [ -3.95417052   4.22254889  -0.14601319]
 [ -6.59947069  -1.00867621   2.29551761]
 [ -0.78942283  -4.15454151   5.87117533]
 [ 13.62292856   0.40038586  -1.36043631]
 [  0.03536684  -5.85950737  -1.86196569]
 [-11.1841298    5.20313078   2.37

## PCA Function (Fixed Dimensionality) Explanation

This version of PCA differs from the previous one in that **the number of output dimensions is explicitly specified (`ndim`)** rather than being determined by variance fraction.

### Key Changes / New Concepts
- **Input `ndim`**: Directly sets the number of principal components to keep.
- **Mean-centering**: `X_m = X - np.mean(X, axis=0)` ensures each feature has zero mean.
- **Weight selection**: `W = Vh.T[:, :ndim]` selects exactly `ndim` principal components.
- **Returns transformed data**: Instead of the weight matrix, the function returns the projected dataset `T = X_m @ W`.


### SVD Decomposition
```python
U, S, Vh = np.linalg.svd(X_m)
W = Vh.T[:, :ndim]
````

* **`U`**: patterns across data points (rows of `X_m`).
* **`S`**: singular values, indicate variance along principal directions.
* **`Vh`**: right singular vectors (transposed), rows correspond to principal directions.
* **`Vh.T[:, :ndim]`**: take first `ndim` columns as principal components for projection.

### Steps

##### 1. **Mean-center the data**

```python
X_m = X - np.mean(X, axis=0)
```

* Ensures PCA works on zero-mean data.

##### 2. **Compute SVD**

* Extracts principal directions (`Vh`) and variance (`S`).

##### 3. **Select principal components**

```python
W = Vh.T[:, :ndim]
```

* Picks the first `ndim` components for projection.

##### 4. **Project data**

```python
T = X_m @ W
```

* Returns the transformed dataset of shape `(n, ndim)`.


### Summary

* This PCA version **explicitly sets the output dimensionality**.
* Performs mean-centering, SVD, and projection onto the top `ndim` principal components.
* Returns the **transformed dataset**, not just the weight matrix.

In [13]:
#!/usr/bin/env python3
"""PCA 1 Module"""
import numpy as np


def pca(X, ndim):
    """Performs PCA on a dataset:
    """
    X_m = X - np.mean(X, axis=0)

    U, S, Vh = np.linalg.svd(X_m)

    W = Vh.T[:, :ndim]

    return X_m @ W

In [15]:
X = np.loadtxt("mnist2500_X.txt")
print('X:', X.shape)
print(X)
T = pca(X, 50)
print('T:', T.shape)
print(T)

X: (2500, 784)
[[1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 ...
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]]
T: (2500, 50)
[[-0.61344587  1.37452188 -1.41781926 ...  0.42685217 -0.02276617
  -0.1076424 ]
 [-5.00379081  1.94540396  1.49147124 ... -0.26249077  0.4134049
   1.15489853]
 [-0.31463237 -2.11658407  0.36608266 ...  0.71665401  0.18946283
  -0.32878802]
 ...
 [ 3.52302175  4.1962009  -0.52129062 ...  0.24412645 -0.02189273
  -0.19223197]
 [-0.81387035 -2.43970416  0.33244717 ...  0.55367626  0.64632309
  -0.42547833]
 [-2.25717018  3.67177791  2.83905021 ...  0.35014766  0.01807652
  -0.31548087]]
